[project]
name = "jupytext-and-marimo-nov-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.5.0",
    "jupytext>=1.19.0.dev0",
    "marimo>=0.18.0",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
]
